services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database_data:/var/lib/postgresql/data

networks:
  clickon-network:
    driver: bridge

volumes:
  database_data:
    driver: local
